framework:
    http_method_override: true
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    router:
        utf8: true
        strict_requirements: null
