nelmio_api_doc:
    documentation:
        info:
            title: 'Fleet API'
            description: 'Fleet management API'
            version: '1.0.0'
    areas:
        default:
            path_patterns: [ ^/api ]
